[package]
name = "sift_cli"
version = "0.1.0-alpha.3"
authors.workspace = true
edition.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
description = "CLI to streamline programmatic workflows with Sift's API"

[dependencies]
anyhow = "1.0.100"
chrono.workspace = true
clap = { version = "4.5.48", features = ["cargo", "derive", "wrap_help"] }
clap_complete = "4.5.58"
crossterm = "0.29.0"
csv = "1.3.1"
dirs = "6.0.0"
flate2 = "1.1.2"
indicatif = "0.18.0"
parquet = "56.2.0"
pbjson-types = { workspace = true }
prost = "0.13.5"
reqwest = "0.12.23"
sift_pbfs = { workspace = true }
sift_rs = { workspace = true }
sift_stream = { workspace = true }
tokio = { version = "1.47.1", features = ["full", "net", "time", "macros", "rt-multi-thread", "signal"] }
tokio-stream = "0.1.17"
tonic = { workspace = true }
tonic-reflection = "0.12"
toml = "0.8.23"
zip = "6.0.0"

[dev-dependencies]
indoc = "2.0.6"

[dependencies.uuid]
version = "1.19.0"
features = ["v4"]

[build-dependencies]
tonic-build = "0.12"
